services:
  - type: web
    name: lms-app
    runtime: docker
    buildCommand: ""
    startCommand: "node server.js"
    plan: standard
    region: ohio
    dockerfilePath: ./Dockerfile
    image:
      url: docker.io/princeayiku/lms-app:latest
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "3000"
      - key: NODE_VERSION
        value: "18.20.8"
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_HOST_URL
        sync: false
      - key: SKIP_API_ROUTES
        value: "true"
      - key: NEXT_SKIP_VALIDATE_ROUTE
        value: "1"
      - key: NEXT_SKIP_DATA_COLLECTION
        value: "1"
      - key: NEXT_SKIP_API_VALIDATION
        value: "1"
      - key: NEXT_SKIP_TYPE_CHECK
        value: "1"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PRISMA_CLIENT_ENGINE_TYPE
        value: "library"
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPEN_AI_KEY
        sync: false
      - key: NEXT_PUBLIC_VOICE_FLOW_KEY
        sync: false
      - key: VOICEFLOW_API_KEY
        sync: false
      - key: VOICEFLOW_KNOWLEDGE_BASE_API
        sync: false
      - key: NEXT_PUBLIC_CLOUD_FRONT_STREAM_URL
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL
        value: "/auth/callback"
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL
        value: "/auth/callback"
      - key: MAILER_PASSWORD
        sync: false
      - key: MAILER_EMAIL
        sync: false
      - key: CLERK_ALLOW_CLOCK_SKEW
        value: "true"
      - key: CLERK_ENCRYPTION_KEY
        sync: false
      - key: NEXT_PUBLIC_EXPRESS_SERVER_URL
        sync: false
      - key: EXPRESS_SERVER_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false 
